//
// Created by 屠昊天 on 2022/5/26.
//


#pragma once
#define MEMORY_SIZE 128 * 1024 * 1024
#define PAGE_SIZE 4096
#define PAGE_COUNT (MEMORY_SIZE / PAGE_SIZE)

#define MEMORY_START 0x80000000

// Kernel
#define KERNEL_START 0x80000000
#define KERNEL_END ((uint64_t)KERNEL_END_ADDRESS)

// Page Bitmap
#define PAGE_BITMAP_ADDRESS ((KERNEL_END % PAGE_SIZE) == 0 ? KERNEL_END : (KERNEL_END / PAGE_SIZE + 1) * PAGE_SIZE)
#define PAGE_BITMAP_SIZE (MEMORY_SIZE / PAGE_SIZE / 8)
#define PAGE_BITMAP_PAGE (PAGE_BITMAP_SIZE % PAGE_SIZE == 0 ? PAGE_BITMAP_SIZE / PAGE_SIZE : PAGE_BITMAP_SIZE / PAGE_SIZE + 1)
#define PAGE_BITMAP_END (PAGE_BITMAP_ADDRESS + PAGE_BITMAP_PAGE * PAGE_SIZE)

// Heap
#define HEAP_START_ADDRESS PAGE_BITMAP_END
#define HEAP_START_PAGE ((HEAP_START_ADDRESS - KERNEL_START) / PAGE_SIZE)


#define MEMORY_END (MEMORY_START + MEMORY_SIZE)
